// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_uJygWqpKYrMAH0vTj9hUMwWTpnMdbo',
    appId: '1:1013601710536:web:8fe0d6ad537bdfe67990fd',
    messagingSenderId: '1013601710536',
    projectId: 'kintagram-app',
    authDomain: 'kintagram-app.firebaseapp.com',
    storageBucket: 'kintagram-app.appspot.com',
    measurementId: 'G-NFN3BPB527',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBofsA-aMkLia0cuHg5qKbhM-wOyAjNeAE',
    appId: '1:1013601710536:android:cbd1a6c837611aa77990fd',
    messagingSenderId: '1013601710536',
    projectId: 'kintagram-app',
    storageBucket: 'kintagram-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa4bCQEwGDIhT_hzHEOvla8IzF6XeKW_E',
    appId: '1:1013601710536:ios:d5643ef6009585ad7990fd',
    messagingSenderId: '1013601710536',
    projectId: 'kintagram-app',
    storageBucket: 'kintagram-app.appspot.com',
    iosClientId: '1013601710536-5235v345a2nrogr67rj7j2lvch0rfchi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kintagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa4bCQEwGDIhT_hzHEOvla8IzF6XeKW_E',
    appId: '1:1013601710536:ios:d5643ef6009585ad7990fd',
    messagingSenderId: '1013601710536',
    projectId: 'kintagram-app',
    storageBucket: 'kintagram-app.appspot.com',
    iosClientId: '1013601710536-5235v345a2nrogr67rj7j2lvch0rfchi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kintagramApp',
  );
}
